/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.io.File;
import java.io.IOException;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.util.Scanner;
/**
 *
 * @author 343418067
 */
public class BusinessResults extends javax.swing.JFrame {

    /**
     * Creates new form BusinessResults
     */
    public BusinessResults() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Since you have selected Business account, here are your suggestions and knowledge on oversharing!");

        jLabel2.setText("- Business accounts on websites and social media are usually created for more exposure to your business.");

        jLabel3.setText("- This way, you can make your company more known online and grow a digital following. ");

        jLabel6.setText("View database of accounts: ");

        jLabel7.setText("Add data to database: ");

        jButton1.setText("View");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setText("- Photos of family or locations can let others know their identities and where they live, potentially making them targets to criminals");

        jLabel9.setText("- Information of your life can give others clues on your passwords or security questions");

        jLabel10.setText("-Pre-k to grade 12 school curriculums teach little to nothing about cyber security");

        jLabel11.setText("- This can however can make you a larger target of hacking or doxxing, especially if you're a small starting business");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addGap(12, 12, 12)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jButton2))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //Initializing variables
        int personalCount = 0;
        int businessCount = 0;
        int count = 0;
        int i = 0;
        //Try catch below to count the lines in info.txt
        try {
            Scanner in = new Scanner(new File("info.txt"));
            while (in.hasNext()) {
                in.nextLine();
                count++;
            }
        } catch(IOException e) {
            System.out.println("Cannot connect to file");
        }
        //Below sets the array of accounts based on the number of lines in the txt file
        Account accounts [] = new Account [count];
        //Below is another try catch that goes through each line and splits the data from delimiter ","
        //Each piece of data is used to make a Business or Personal account based on the word "Business" or "Personal" at the end
        try {
            Scanner in = new Scanner(new File("info.txt"));
            while (in.hasNext()) {
                String output = in.nextLine();
                String data [] = output.split(",");
                //Prints out name, username, and type of account
                System.out.print(data[2] + " Name: " + data[1] + " " + data[0] + " Type: " + data[9]);
                if (data[9].equals("Business")) {
                    accounts[i] = new BusinessAccount(data[0],data[1],new Date(Integer.parseInt(data[3]),Integer.parseInt(data[4]),Integer.parseInt(data[5])),data[2],data[6],Boolean.parseBoolean(data[7]),Integer.parseInt(data[8]));
                    i++;
                    System.out.println("");
                } else {
                    accounts[i] = new PersonalAccount(data[0],data[1],new Date(Integer.parseInt(data[3]),Integer.parseInt(data[4]),Integer.parseInt(data[5])),data[2],data[6],Boolean.parseBoolean(data[7]),Integer.parseInt(data[8]));
                    i++;
                    System.out.println("");
                }
            }
            //For every element in accounts array, if it's a business or personal account, it adds 1 to it's respective counter
            for (int e = 0; e < accounts.length; e++) {
                if (accounts[e] instanceof BusinessAccount) {
                    businessCount++;
                } else {
                    personalCount++;
                }
            }
            //Uses the counters to say how many of which type of account is stored
            System.out.println("Business Accounts Stored: " + businessCount);
            System.out.println("Personal Accounts Stored: " + personalCount);
        } catch (FileNotFoundException e) {
            //If file is not found, prints error message
            System.out.println("Cannot connect to file");
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String lastname = AccountCreation.account.getLastName();
        String firstname = AccountCreation.account.getFirstName();
        String username = AccountCreation.account.getUsername();
        String password = AccountCreation.account.getPassword();
        boolean choiceText;
        int number = 0;
        
        Date userDOB = AccountCreation.account.getDOB();
        int userDay = userDOB.getDay();
        int userMonth = userDOB.getMonth();
        int userYear = userDOB.getYear();
        if (AccountCreation.account instanceof PersonalAccount) {
            choiceText = ((PersonalAccount) AccountCreation.account).getChoice();
        } else {
            choiceText = ((BusinessAccount) AccountCreation.account).getChoice();
        }
        String choice = Boolean.toString(choiceText);
        if (AccountCreation.account instanceof BusinessAccount) {
            number = ((BusinessAccount) AccountCreation.account).getDailyInteractions();
        } else {
            number = ((PersonalAccount) AccountCreation.account).getTimeOnline();
        }
       
        try {
            FileWriter w = new FileWriter(new File("info.txt"), true);
            if (AccountCreation.account instanceof BusinessAccount) { 
                w.write(lastname + "," + firstname + "," + username + "," + userDay + "," + userMonth + "," + userYear + "," + password + "," + choice + "," + number + "," + "Business" + System.lineSeparator());
            } else {
                w.write(lastname + "," + firstname + "," + username + "," + userDay + "," + userMonth + "," + userYear + "," + password + "," + choice + "," + number + "," + "Personal" + System.lineSeparator());
            }
            w.close();
        } catch(IOException e) {
            System.out.println("Cannot write to file");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusinessResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusinessResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusinessResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusinessResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BusinessResults().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
